S3 provider updates and general cleanup
coldbox-modules/cbfs pull request #16
Opened 2022-11-15 20:00 UTC by grantcopley

2022-11-16 20:03 UTC, jclausen requested changes
Looks good! A few cleanup suggestions

2022-11-16 23:15 UTC, grantcopley commented on models/providers/S3Provider.cfc
> +		if ( this.fileExists( path ) ) {
@jclausen  buildDirectoryPath() isn't doing trailing slash stripping, it's ensuring that there is a trailing slash when performing directory operations. This ensures that the paths are properly handled as pseudo folders in S3. Without the trailing slash, it becomes very confusing if we are working with just a empty file versus an actual folder, which is why I separated the two.

2022-11-17 17:40 UTC, jclausen approved these changes
Merge away!

2022-11-23 11:07 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +		return this.fileExists( path );
I would prefer if the API for files stays simplified to just `exists()` like we had.  I know we have to change it to differentiate between files and directories.  But since this is file centric.  Let's do `missing()` and `exists()` for files. For directories we can use another naming convention.

2022-11-23 11:07 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +	boolean function fileMissing( required string path ){
Make this `missing()` like it was.

2022-11-23 11:08 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +		return this.fileExists( path );
Now, why would a directoryExists() in the base call the fileExists()

2022-11-23 11:08 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +		return this.fileExists( path );
Also, will this work in adobe since the CFML function is called `directoryExists()` https://cfdocs.org/directoryexists

2022-11-23 11:08 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +		variables.properties.path = this.normalizePath( variables.properties.path );
why use `this` ?

2022-11-23 11:09 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +		if ( !arguments.overwrite && this.fileExists( arguments.path ) ) {
Why use `this` ?

2022-11-23 11:09 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +		arguments.path = this.buildDiskPath( arguments.path );
Why use `this` ?

2022-11-23 11:09 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +			variables.ensureDirectoryExists( containerDirectory );
Why the scoping?

2022-11-23 11:14 UTC, lmajano commented on models/providers/S3Provider.cfc
> +		return structKeyExists( variables, "s3" );
Use `isNull()` in case full null support is being used

2022-11-23 11:18 UTC, lmajano commented on models/providers/S3Provider.cfc
> +		arguments.directory = variables.buildDirectoryPath( arguments.directory );
Did you test if sending a deleteobject on the folder would recurse automatically instead of doing this manually?

2022-11-23 19:59 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +		return variables.jFiles.readString( getJavaPath( variables.ensureFileExists( arguments.path ) ) );
missed this one

2022-11-23 19:59 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +		return variables.jFiles.readAllBytes( getJavaPath( variables.ensureFileExists( arguments.path ) ) );
missed this one

2022-11-23 19:59 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +			.getLastModifiedTime( getJavaPath( variables.ensureFileExists( arguments.path ) ), [] )
missed this one

2022-11-23 19:59 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +			// variables.jFiles.walkFileTree(
You never answered this?

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return variables.ensureRecordExists( arguments.path ).path;
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return variables.ensureRecordExists( arguments.path ).lastModified;
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return getMimeType( variables.ensureRecordExists( arguments.path ).path );
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return variables.ensureRecordExists( arguments.path );
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return hash( variables.ensureRecordExists( arguments.path ).contents, arguments.algorithm );
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		variables.ensureRecordExists( arguments.path ).mode = arguments.mode;
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return variables.ensureRecordExists( arguments.path ).visibility == "public";
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return isWritable( arguments.path ) || variables.ensureRecordExists( arguments.path ).visibility == "readonly";
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return variables.ensureRecordExists( arguments.path ).visibility == "private";
missed this one

2022-11-23 20:00 UTC, lmajano commented on models/providers/RamProvider.cfc
> +		return variables.ensureRecordExists( arguments.path ).symbolicLink;
missed this one

2022-11-23 20:01 UTC, lmajano commented on models/providers/RamProvider.cfc
> +			var sourceRecord = variables.ensureRecordExists( arguments.source );
missed this one

2022-11-23 20:01 UTC, lmajano commented on models/providers/RamProvider.cfc
> +			var oldRecord = variables.ensureRecordExists( arguments.source );
missed this one

2022-11-23 20:01 UTC, lmajano commented on models/providers/RamProvider.cfc
> +			var dirRecord = variables.ensureRecordExists( arguments.directory );
missed this one

2022-11-24 09:13 UTC, merged