#25 Introduce a file object and proxy method calls to the disk to provide a more fluent API
coldbox-modules/cbfs pull request #32
Opened 2022-12-06 18:48 UTC by grantcopley

2022-12-06 23:38 UTC, jclausen requested changes
One small change and then this looks great on my end.

2022-12-08 16:47 UTC, grantcopley commented on models/testing/AbstractDiskSpec.cfc
> +					var files = [ "some_file.txt", "another_file.txt" ];
@jclausen Not following. What should I prefix it with - the name of the CFML engine?

2022-12-12 19:41 UTC, jclausen approved these changes

2022-12-20 14:53 UTC, lmajano commented on models/providers/RamProvider.cfc
> -	/**************************************** STREAM METHODS ****************************************/
I think this is heavy handed. The RAM disk can still produce streams and it was working and useful

2022-12-20 14:53 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +		return createObject( "component", "cbfs.models.File" ).init( argumentCollection = arguments );
Can you use the `new` notation please

```
new File( argumentCollection = arguments  )
```

2022-12-20 14:53 UTC, lmajano commented on models/File.cfc
> +component accessors="true" {
Please add the header allf iles have for consistency, with purpose and copyright info

2022-12-20 14:54 UTC, lmajano commented on models/File.cfc
> +	function init( required disk, required path ){
Add cfc docs

2022-12-20 14:54 UTC, lmajano commented on models/File.cfc
> +		invoke( getDisk(), "create", arguments );
Why didn't you just do `getDisk().create( argumentCollection = arguments )` much faster than `invoke`

2022-12-20 14:55 UTC, lmajano commented on models/File.cfc
> +		return createObject( "component", "cbfs.models.File" ).init(
use the `new` approach please

2022-12-20 14:55 UTC, lmajano commented on models/File.cfc
> +		return createObject( "component", "cbfs.models.File" ).init(
same here

2022-12-20 14:56 UTC, lmajano commented on test-harness/tests/specs/providers/RamDiskSpec.cfc
> -
Please keep these

2022-12-20 14:56 UTC, lmajano commented
Small changes and I can merge and release

2022-12-21 18:39 UTC, merged