Feature/add s3 disk provider
coldbox-modules/cbfs pull request #6
Opened 2021-02-16 18:28 UTC by jclausen

This feature adds an S3Provider to the storage options.  Note that tests will fail until the following PR is merged in to `s3sdk` development :https://github.com/coldbox-modules/s3sdk/pull/32

This also corrects some functionality and tests in the Abstract, Local, and Mock providers

2021-03-05 15:23 UTC, lmajano requested changes

2021-03-05 15:23 UTC, lmajano commented on box.json
> +        "s3sdk":"be"
This should be a dependency not a dev dependency though

2021-03-05 15:23 UTC, lmajano commented on box.json
> +        "s3sdk":"be"
Also, you can change it to the latest, we incorporated all the changes

2021-03-05 15:23 UTC, lmajano commented on box.json
> +		"modules/s3sdk"
Can you just add `modules/**` please

2021-03-05 15:23 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +        if ( listLen( this.name( arguments.path ), "." ) > 1 ) {
Great catch! 👍

2021-03-05 15:23 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +    private function isDirectoryPath( required path ) {
Can you add the cfc docs for it please

2021-03-05 15:23 UTC, lmajano commented on models/AbstractDiskProvider.cfc
> +            return isDirectoryPath( arguments.path );
Hmm, what is the intent of this? Shouldn't the above deal with it?

2021-03-05 15:23 UTC, lmajano commented on models/providers/LocalProvider.cfc
>      public IDisk function setVisibility( required string path, required string visibility ) {
Can we add some cfc docs here please, well everywhere we can :)

2021-03-05 15:23 UTC, lmajano commented on models/providers/LocalProvider.cfc
>      this.permissions = {
I actually see no point in making these public variablesin in the `this` scope when they are static in nature. I suggest moving them to `variables.PERMISSIONS` to denote a static lookup

2021-03-05 15:23 UTC, lmajano commented on models/providers/LocalProvider.cfc
> +            if ( isDirectory( arguments.path ) ) {
This entire function is repetitive in nature.  Just inflate the `path` to an array and always treat it as an array instead of having two branches of execution of the same code.

2021-03-05 15:23 UTC, lmajano commented on models/providers/S3Provider.cfc
> +component accessors="true" implements="cbfs.models.IDisk" {
Please make sure you add all cfc docs

2021-03-05 15:23 UTC, lmajano commented on models/providers/S3Provider.cfc
> +    setting requestTimeout="500";
This is only used when the CFC is created, why is it here?

2021-03-05 15:23 UTC, lmajano commented on models/providers/S3Provider.cfc
> +component accessors="true" implements="cbfs.models.IDisk" {
Shouldn't this be a singleton?

2021-03-05 15:23 UTC, lmajano commented on models/providers/S3Provider.cfc
> +component accessors="true" implements="cbfs.models.IDisk" {
This provider is not inheriting from the abstract one, why?

2021-03-05 15:23 UTC, lmajano commented on models/providers/S3Provider.cfc
> +            variables.s3 = application.wirebox.getInstance( "AmazonS3@s3sdk" );
Why go to the `application` scope. All providers are created by WireBox especially via the service. So there should be no need to break the encapsulation here.

2021-03-05 22:53 UTC, jclausen commented on models/providers/S3Provider.cfc
> +    setting requestTimeout="500";
Oops!  Development code. 😱

2021-03-05 22:53 UTC, jclausen commented on models/providers/S3Provider.cfc
> +            variables.s3 = application.wirebox.getInstance( "AmazonS3@s3sdk" );
I'll try moving this to injection then

2021-03-05 22:53 UTC, jclausen commented on models/AbstractDiskProvider.cfc
> +            return isDirectoryPath( arguments.path );
No, because of the way that this method is used, if the path did not exist, it would throw even if you passed a directory path in to it.  The `isDirectoryPath` fallback ensures that it evaluates the path and whether it is a directory pattern.

2021-03-05 22:53 UTC, jclausen commented on models/providers/LocalProvider.cfc
>      this.permissions = {
I actually could see them being used in other contexts, though I'm fine with moving them to `variables`

2021-03-05 22:53 UTC, jclausen commented on models/providers/LocalProvider.cfc
> +            if ( isDirectory( arguments.path ) ) {
Can do.  I was just following the previous implementation.

2021-03-05 22:53 UTC, jclausen commented on models/providers/S3Provider.cfc
> +component accessors="true" implements="cbfs.models.IDisk" {
It gets created as a singleton, anyway, when the disk objects are created  - like interceptors, right?  I was just following the lead of `LocalProvider`

2021-03-05 22:53 UTC, jclausen commented on models/providers/S3Provider.cfc
> +component accessors="true" implements="cbfs.models.IDisk" {
I can't remember now. I'll double check.  It may be an omission on my part

2021-03-05 22:53 UTC, jclausen commented on box.json
> +        "s3sdk":"be"
I made this a dev dependency because it doesn't need to be a hard dependency of the module - but it needs to be there in dev to test this.   If an attempt to configure the S3 provider is made in an application, then an error is thrown when an attempt to instantiate the SDK is made. 

This follows the pattern of Laravel's disk drivers, where there are caveats in the documentation that tell you, "if you want to use this driver, then you need to add X to you package.json"

I'm open to making it a dependency, but if someone tries to an instantiate an s3 driver without the s3 module installed, they will know the root cause right away.

2021-03-05 22:55 UTC, jclausen commented on models/AbstractDiskProvider.cfc
> +    private function isDirectoryPath( required path ) {
Will do

2021-03-05 23:24 UTC, jclausen commented on models/providers/S3Provider.cfc
> +component accessors="true" implements="cbfs.models.IDisk" {
Looking at `models/dsl/cbfsDSL.cfc` I don't think you would want to mark these as singletons because then wirebox would mutate a second instance of the same provider.

2021-03-05 23:29 UTC, jclausen commented on models/providers/S3Provider.cfc
> +            variables.s3 = application.wirebox.getInstance( "AmazonS3@s3sdk" );
I changed this to inject wirebox.  Because of my notes above on not requiring S3SDK for the whole module, I'm hesitant to try to inject that object directly.  If we decided to require it, it's a no brainer.  If we inject it, then an attempt to instantiate blows up with a much more cryptic Wirebox error and stack trace - rather than the specific Stack which points to the `configure` method attempt to instantiate.

2021-03-05 23:30 UTC, jclausen commented on box.json
> +        "s3sdk":"be"
@lmajano I will let you decide on the dependency.  I can totally see some CF dev installing this module and complaining because it installed S3, when they don't want to use S3 😄

2021-03-05 23:37 UTC, jclausen commented on box.json
> +        "s3sdk":"be"
> Also, you can change it to the latest, we incorporated all the changes

Done

2021-03-06 20:23 UTC, elpete requested changes

2021-03-06 20:23 UTC, elpete commented on models/providers/S3Provider.cfc
> +            arguments.properties.tempDirectory = "/includes/temp";
Just curious why we are using `/includes/temp` instead of something like CFML's [`getTempDirectory`](https://cfdocs.org/gettempdirectory)

2021-03-06 20:23 UTC, elpete commented on models/providers/S3Provider.cfc
> +            abort;
Not sure you want this `abort` in there.

2021-03-06 20:23 UTC, elpete commented on models/providers/S3Provider.cfc
> +        } catch ( any e ) {
I think you can leave out this catch block and it will have the same effect.

2021-03-06 20:23 UTC, elpete commented on models/providers/S3Provider.cfc
> +    string function temporaryURL( required path, numeric expiration ) {
Should there be a default expiration?  Or does a `null` expiration mean forever?

Also, does this compile down on line 415 without an `isNull` check?

2021-03-06 20:23 UTC, elpete commented on models/providers/S3Provider.cfc
> +        } catch ( any e ) {
I don't think this `catch` block is necessary.

2021-03-06 20:23 UTC, elpete commented on models/providers/S3Provider.cfc
> +        } catch ( any e ) {
I don't think this `catch` block is necessary.

2021-03-06 20:23 UTC, elpete commented on models/providers/S3Provider.cfc
> +    private function isWindows() {
This function is only used in the `LocalProvider`, right?

2021-03-06 20:23 UTC, elpete commented on test-harness/box.json
> +        "testbox":"^4.2.1+400"
`devDependency`?

2021-03-07 16:37 UTC, jclausen commented on models/providers/S3Provider.cfc
> +            abort;
Doh! Debug code.

2021-03-07 16:37 UTC, jclausen commented on models/providers/S3Provider.cfc
> +            arguments.properties.tempDirectory = "/includes/temp";
Good call. I'll modify that.

2021-03-07 16:47 UTC, jclausen commented on models/providers/S3Provider.cfc
> +        } catch ( any e ) {
I did not know that it would rethrow without the final `catch( any e )`  Thanks! :)

2021-03-07 16:48 UTC, jclausen commented on models/providers/S3Provider.cfc
> +    private function isWindows() {
Good catch!

2021-03-07 17:58 UTC, jclausen commented on models/providers/S3Provider.cfc
> +    string function temporaryURL( required path, numeric expiration ) {
I've moved the default expiration to this method.  Good catch!

2021-03-07 18:01 UTC, jclausen commented
I've resolved all of @elpete and @lmajano 's feedback on this PR, with the exception of one architectural question:

Should we make the external module that any provider that uses a hard dependency of the module, or should we put caveats in the documentation that they will need to add that as a dependency.   

My recommendation is the latter ( see here : https://github.com/coldbox-modules/cbfs/pull/6#discussion_r588770780 ) . I would prefer that the module install be lean and mean and, if they want to enable other providers, they can do so.

2021-03-08 05:14 UTC, elpete commented
I agree that we not include the SDK as a hard dependency. You could easily imagine a world where this S3Provider is not core but a module itself. Then it would make sense to require the s3sdk as a dependency.

2021-03-08 15:25 UTC, lmajano commented on box.json
> +        "s3sdk":"be"
Yea, I get it.  It's a hard decision.  But some part of me thinks, just add the dependency, it does nothing if it's there, just takes up space basically. However, the developer does nothing to just use it.  If it's not there, they will get errors and then follow to install.  Now, what happens when they use a version that is not compatible with it? They move to a new major version and tthen it also breaks.  

I think the way to go is the thte package comes with it's dependencies, wether you use them or not.  In reality, the only downsize is disk space.

2021-03-08 15:26 UTC, lmajano commented on models/providers/S3Provider.cfc
> +            variables.s3 = application.wirebox.getInstance( "AmazonS3@s3sdk" );
This is a ColdBox module and it needs to depend on the WireBox.  So I would not consider going to the app scope for it's usage.

2021-03-08 15:28 UTC, lmajano commented
I mentioned in my comment that NOT including the dependency will cause more issues than what it tries to solve.  The package should come with it's dependencies already baked.  If not, you are providing it in a broken state and having less control of what version to use.  

I am also working on making modules completely isolated, so they can use ANY version of any dependency module and have multiple module versions in your app like OSGI.

2021-03-08 15:50 UTC, elpete commented
> I mentioned in my comment that NOT including the dependency will cause more issues than what it tries to solve. The package should come with it's dependencies already baked. If not, you are providing it in a broken state and having less control of what version to use.

So how about we separate this module entirely? Pull it out into its own module. Then we get both - small install plus module with all its dependencies.

2021-03-08 15:51 UTC, elpete commented
Prior art example for cbmailservices: https://www.forgebox.io/view/send-grid-protocol

2021-03-08 16:26 UTC, lmajano commented
Ok, that I can get on board with. We can leave `cbfs` the core with it's basic providers and anything extra can be `cbfs-s3` as a separate module. I can get on board with that.

2021-03-08 16:31 UTC, jclausen commented
Can I push back a bit?  While we're still developing this module to its first release, can we merge this in so that there's only one place to make changes to anything we modify in the method signatures or return expectations of the interface.  

Developing a module in pre-release, and then developing a separate module which has to run CI jobs to that pre-release code is a PIB. :)

2021-03-08 16:38 UTC, elpete commented
I think that's fair.

So, 1. Bundle the S3 Provider with the s3sdk.
2. Split it out to its own module when the library is stable.

On Mon, Mar 8, 2021, 9:31 AM Jon Clausen <notifications@github.com> wrote:

> Can I push back a bit? While we're still developing this module to its
> first release, can we merge this in so that there's only one place to make
> changes to anything we modify in the method signatures or return
> expectations of the interface.
>
> Developing a module in pre-release, and then developing a separate module
> which has to run CI jobs to that pre-release code is a PIB. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coldbox-modules/cbfs/pull/6#issuecomment-792880008>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AATWYXWI5WC3DKIMYKT4UITTCT3WRANCNFSM4XW5YHIA>
> .
>

2021-03-08 16:41 UTC, elpete commented
> For example, I think it's janky that we have two `ensure` methods, one doesn't really `ensure` anything - it throws an error ( ensureFileExists ), while the other checks and creates the directory.
> 
> IMHO, a method named `ensure` should touch or create the destination, whereas a function that is expected to throw any error should have an `OrFail` in the method name ( `fileExistsOrFail` )

Good point. The other verb I tend to use besides `orFail` is `guard`. I do like that `exists` and `existsOrFail` is something that cborm and Quick have.

2021-03-08 16:51 UTC, jclausen commented
> Good point. The other verb I tend to use besides `orFail` is `guard`. I do like that `exists` and `existsOrFail` is something that cborm and Quick have.

If we all agree on `existsOrFail` I can change that in this PR.  

I would  appreciate keeping all of these in the same place and then breaking them out to separate modules on initial release.  

There are two other storage drivers I'd like to implement, off the top of my head :  SQL Server Filestream, and MongoDB Grid FS.  Once we get those implemented, this would be a viable solution for just about any media storage needs

2021-03-08 17:55 UTC, lmajano commented
I am ok with leaving them here for now until we go stable.  Please note that the disk service is not implemented yet and that is the driving force as well to get all these providers working. I will separate some time to tackle this, unless someone wants a hack at it.

As for the `existsOrFail()` I love that.

2021-03-08 17:56 UTC, lmajano commented
I woudl suggest two functions: `exists()` and `existsOrFail()` give the option.

2022-04-01 21:10 UTC, merged